### ISSUE TITLE
Where did the minized_petalinux tags go?

### ISSUE THREAD

**Issue by hugolm84** [Avnet/hdl#10]
According to the [MiniZed_Petalinux_HDF_2017_1_02-Tutorial.pdf](http://zedboard.org/sites/default/files/design/MiniZed_PetaLinux_HDF_2017_1_02-Tutorial.zip), I need to clone this HDL repository from the minized_petalinux_MINIZED_20170810_010906 tag.

This tag is not longer present, which one has replaced it?

**Comment by zedhed** [comment]
Hello hugolm84,

The tag is still present, it just does not show up in the Github search any longer for some reason.  You can access the tag by including it in the HDL repo URL like this:

https://github.com/Avnet/hdl/tree/minized_petalinux_MINIZED_20170810_010906

Also, please post any future issues you encounter on the forums at ZedBoard.org since those forums are regularly monitored by the Zed design group.

Best Regards,

-Kevin
